namespace SageBinaryData
{
    public enum UIFixedElementId
    {
        INVALID = -1,
        ENERGY_METER,
        SELL_BUTTON,
        TOGGLE_REPAIR_BUTTON,
        TOGGLE_POWER_BUTTON,
        ATTACK_MOVE_BUTTON,
        FORCE_ATTACK_BUTTON,
        FORCE_MOVE_BUTTON,
        REVERSE_MOVE_BUTTON,
        WAYPOINT_MODE_BUTTON,
        PLANNING_MODE_BUTTON,
        STANCE_AGGRESSIVE_BUTTON,
        STANCE_GUARD_BUTTON,
        STANCE_HOLD_GROUND_BUTTON,
        STANCE_HOLD_FIRE_BUTTON,
        MAIN_STRUCTURE_TAB,
        OTHER_STRUCTURE_TAB,
        INFANTRY_TAB,
        VEHICLE_TAB,
        AIRCRAFT_TAB
    }
}
