namespace SageBinaryData
{
    public enum AISpecialPowerInstanceType
    {
        SPECIAL_POWER_BASIC_SELF_BUFF,
        SPECIAL_POWER_AOE_BUFF,
        SPECIAL_POWER_CAPTURE_BUILDING,
        SPECIAL_POWER_ENEMY_TYPE_KILLER_STRUCTURES,
        SPECIAL_POWER_RANGED_AOE_ATTACK,
        SPECIAL_POWER_MOVEMENT,
        SPECIAL_POWER_BUILD_CONYARD,
        SPECIAL_POWER_BUFF_ALLY,
        SPECIAL_POWER_SUPERWEAPON,
        SPECIAL_POWER_REINFORCEMENT,
        SPECIAL_POWER_HEAL_AOE,
        SPECIAL_POWER_TARGET_STEALTH,
        SPECIAL_POWER_SPECIFIC_UNIT,
        SPECIAL_POWER_SEED_TIBERIUM,
        SPECIAL_POWER_EMP_COUNTER,
        SPECIAL_POWER_DECOY_ARMY,
        SPECIAL_POWER_STANCEBATTLE,
        SPECIAL_POWER_STANCEAGGRESSIVE,
        SPECIAL_POWER_STANCEHOLDGROUND,
    }
}
